Registreringsapp/registrationapp/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :api_keys, controller: "api_key"
  
  constraints lambda { |req| !req.session[:user_id].blank? } do
    root :to => "api_key#index", :as => "dashboard"   
  end
  
  root :to => "sessions#new"
  
  get  '/login'   => 'sessions#new'
  post '/login'   => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/register' => 'users#new'
  get '/newapp' => 'api_key#new'
  get '/request' => 'api_key#create'
  get '/revoke' => 'api_key#destroy'
  get '/index' => 'api_key#index'

end

Registreringsapp/registrationapp/app/models/api_key.rb
class ApiKey < ActiveRecord::Base
  belongs_to :user
  
  validates :api_key, presence: true
  validates :api_key, uniqueness: true
  validates :app_name, presence: true
end

Registreringsapp/registrationapp/app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true
  validates :email, uniqueness: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :password, presence: true
  
  has_many :api_key, :dependent => :destroy
  
  has_secure_password
end

Registreringsapp/registrationapp/app/controllers/api_key_controller.rb
class ApiKeyController < ApplicationController
  before_action :checkuniquekey, only: [:create]
  
  def index    
    if logged_in?
      if current_user.email == "christoffer.goude@gmail.com"
        @apikeys = ApiKey.all
      else
        @apikeys = ApiKey.where(:user_id => current_user.id)
      end
    else
      flash[:login] = 'Please begin by logging in.'
      redirect_to root_url
    end
  end
  
  def new
    @api_key = ApiKey.new
  end
  
  def create
    @api_key = ApiKey.new(key_params)

    @api_key.api_key = SecureRandom.hex
    @api_key.user_id = current_user.id
    
    if @api_key.save
      flash[:key] = 'You have been assigned an API key.'
      redirect_to index_path
    else
      flash[:key] = 'Something went wrong, please try again!'
      redirect_to index_path
    end
  end
  
  def destroy ()
    # Remove a users API key
    if ApiKey.destroy_all(:id => params[:id])
      flash[:admin] = "The chosen API key was revoked!"
    else
      flash[:admin] = "There was an issue with revoking this key!"
    end   
    redirect_to index_path
  end
  
  def show
  end
  
  def checkuniquekey
    ApiKey.where(:user_id => current_user.id).blank?
  end
  
  private
      # Never trust parameters from the scary internet, only allow the white list through.
    def key_params
      params.require(:api_key).permit(:app_name)
    end
end

Registreringsapp/registrationapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include SessionsHelper
end

Registreringsapp/registrationapp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    #Called to show login form
  end
  
  # Called when a users tries to login
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      
      # Redo admin check via helper
      redirect_to index_path
    else
      # Create an error message.
      flash[:login] = 'Invalid email/password combination!'
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
end

Registreringsapp/registrationapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:api_key)
    @apikeys = ApiKey.all
    
    if logged_in?
      unless current_user.email == "christoffer.goude@gmail.com"
        flash[:key] = 'You do not have access to that page!'
        redirect_to authorized_path
      end
    else
      flash[:login] = 'Please begin by logging in.'
      redirect_to root_url
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end
  
  # GET /users/:id
  def show
    if logged_in?
      unless current_user.email == "christoffer.goude@gmail.com"
        flash[:key] = 'You do not have access to that page!'
        redirect_to authorized_path
      end
    else
      flash[:login] = 'Please begin by logging in.'
      redirect_to root_url
    end
  end
  
  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save     
      log_in @user    
      flash[:key] = 'Welcome to the registration app!'
      redirect_to authorized_path
    else
      if @user.email.present?
        flash[:register] = 'This email adress is not valid or already in use!'
      else
        flash[:register] = 'You must enter an email adress!'
      end
      
      redirect_to register_path
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def login
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

Registreringsapp/registrationapp/app/helpers/api_key_helper.rb
module ApiKeyHelper
end

Registreringsapp/registrationapp/app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
   # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

Registreringsapp/registrationapp/app/helpers/users_helper.rb
module UsersHelper
end

Registreringsapp/registrationapp/app/views/api_key/index.html.erb
<div class="row">
	<div class="large-12 columns">
		<h1>Key overview</h1>
	</div>
</div>

<% @apikeys.each do |key| %>
	<div class="row">
		<div class="large-10 columns">
			<p class="panel">
				<b>Application name:</b> <%= key.app_name %> <b>API Key:</b> <%= key.api_key %>
			</p>
		</div>
		<div class="large-2 columns">
			<%= button_to "Remove", {:controller => "api_key", :action => "destroy", :id => key.id}, {:method => :delete, :class => "panel button alert expand"} %>
		</div>						
	</div>
<% end %>

<% if flash[:admin] %>
    <div class="row">
    	<div class="large-12 columns">
    		<div data-alert class="alert-box warning">
			  <%= flash[:admin] %>
			  <a href="#" class="close">&times;</a>
			</div>
		</div>
	</div>
<% end %>

<div class="row">
	<div class="large-12 columns">
		<%= link_to 'New application', newapp_path, {:class => "button secondary expand"} %>
	</div>
</div>

<div class="row">
	<div class="large-12 columns">
		<%= link_to 'Log Out', logout_path, {:class => "button secondary expand"} %>
	</div>
</div>

Registreringsapp/registrationapp/app/views/api_key/new.html.erb
<div class="row">
	<div class="large-12 columns">
		<h1>New application</h1>
	</div>
</div>
<div class="row">
	<div class="large-12 columns">
		<p class="panel">Here you can create a new application and receive an API key.</p>
	</div>
</div>

<% if flash[:key] %>
    <div class="row">
    	<div class="large-12 columns">
    		<div data-alert class="alert-box warning">
			  <%= flash[:key] %>
			  <a href="#" class="close">&times;</a>
			</div>
		</div>
	</div>
<% end %>

<%= form_for(@api_key) do |f| %>	
	<div class="row">
		<div class="large-12 columns">
			<div class="field">
			    <%= f.label :app_name %><br>
			    <%= f.text_field :app_name %>
		  	</div>
	  	</div>
		<div class="large-12 columns">
		  	<div class="actions">
		    	<%= f.submit "Register new application", :class => "button expand" %>
		  	</div>	  	
	  	</div>
	</div>
<% end %>

<div class="row">
	<div class="large-12 columns">
		<%= link_to 'Log Out', logout_path, {:class => "button secondary expand"} %>
	</div>
</div>

Registreringsapp/registrationapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "API Key Application" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>	
	<nav class="top-bar" data-topbar role="navigation">
	  <ul class="title-area">
	    <li class="name">
	      <h1><a href="#">RegistrationAPP</a></h1>
	    </li>
	    <% if logged_in? %>
	    	<li class="toggle-topbar"><a href="#"><span>Logged in</span></a></li>
	  	<% end %>
	  </ul>
	
	  <section class="top-bar-section">
	    <!-- Right Nav Section -->
	    <ul class="right">
	    	<% if logged_in? %>
	      		<li><a href="#">Logged in as <%= current_user.email %></a></li>
	      	<% end %>
	    </ul>
	  </section>
	</nav>

    <%= yield %>
  </body>
</html>

Registreringsapp/registrationapp/app/views/users/edit.html.erb
<div class="row">
	<div class="large-12 columns">
		<h1>Editing user</h1>
	</div>
</div>
<%= render 'form' %>
<div class="row">
	<div class="large-12 columns">
		<%= link_to 'Show', @user, {:class => "button secondary"} %>
		<%= link_to 'Back', users_path, {:class => "button secondary"} %>
	</div>	
</div>

Registreringsapp/registrationapp/app/views/users/index.html.erb
<div class="row">
	<div class="large-6 columns">
		<p><b>USERNAME</b></p>
	</div>
	<div class="large-6 columns">
		<p><b>PASSWORD</b></p>
	</div>
</div>
<% @users.each do |user| %>
	<div class="row">
		<div class="large-6 columns">
			<p><%= user.email %></p>
		</div>
		<div class="large-6 columns">
			<p><%= user.password %></p>
		</div>
	</div>
<% end %>
<div class="row">
	<div class="large-12 columns">
		<%= link_to 'Log Out', logout_path, {:class => "button secondary expand"} %>
	</div>
</div>

Registreringsapp/registrationapp/app/views/users/login.html.erb
<div class="row">
	<div class="large-12 columns">
		<h1>Login</h1>
	</div>
</div>

<%= render 'form' %>

<div class="row">
	<div class="large-12 columns">
		<%= link_to 'Back', users_path, {:class => "button secondary"} %>
	</div>
</div>

Registreringsapp/registrationapp/app/views/users/new.html.erb
<div class="row">
	<div class="large-12 columns">
		<h1>Register</h1>
	</div>
</div>

<% if flash[:register] %>
    <div class="row">
    	<div class="large-12 columns">
    		<div data-alert class="alert-box warning">
			  <%= flash[:register] %>
			  <a href="#" class="close">&times;</a>
			</div>
		</div>
	</div>
<% end %>

<%= form_for(@user) do |f| %>	
	<div class="row">
		<div class="large-12 columns">
			<div class="field">
			    <%= f.label :email %><br>
			    <%= f.text_field :email %>
		  	</div>
	  	</div>
		<div class="large-12 columns">
		  	<div class="field">
			    <%= f.label :password %><br>
			    <%= f.password_field :password %>
		  	</div>
		</div>
		<div class="large-12 columns">
		  	<div class="actions">
		    	<%= f.submit "Register", :class => "button expand" %>
		  	</div>	  	
	  	</div>
	</div>
<% end %>


<div class="row">
	<div class="large-12 columns">
		<%= link_to "Back", login_path, {:class => "button secondary expand"} %>
	</div>
</div>

Registreringsapp/registrationapp/app/views/users/show.html.erb
<div class="row">
	<div class="large-12 columns">
		<h1>User</h1>
	</div>
</div>
<div class="row">
	<div class="large-6 columns">
		<p>
			<strong>Email:</strong>
		  	<%= @user.email %>
		</p>
	</div>
	<div class="large-6 columns">
		<p>
			<strong>Password:</strong>
  			<%= @user.password %>
		</p>
	</div>
</div>
<div class="row">
	<div class="large-12 columns"> 
		<%= link_to 'Back', login_path, {:class => "button secondary"} %>
	</div>
</div>